/* Copyright (c) 2026 tabnas, MIT License */

// Generated by ../embed-translate.js. Edit tabnas.plugin.json or alchemy/*,
// then run npm run embed.

type TranslationPart = Readonly<{
  entry: string
  source?: string
}>

type TranslationParts = Readonly<{
  manifest: string
  lift?: TranslationPart
  render?: TranslationPart
}>

const TRANSLATION: TranslationParts = Object.freeze({
  manifest: `{
  "$schema": "https://tabnas.dev/schema/plugin.schema.json",
  "name": "@tabnas/json",
  "go": "github.com/tabnas/json/go",
  "description": "A standard JSON parser (RFC 8259) for the tabnas engine.",
  "engine": "@tabnas/parser",
  "extensions": [
    ".json"
  ],
  "mediaTypes": [
    "application/json"
  ],
  "languageId": "json",
  "pluginKind": "grammar",
  "grammarKind": "data",
  "lexStream": "clean",
  "syncGroups": [
    "end",
    "comma",
    "close"
  ],
  "specDir": "test/spec",
  "clib": {
    "dir": "go/clib",
    "library": "libtabnasjson",
    "abi": "v1",
    "errorCodes": [
      "usage",
      "grammar",
      "handle",
      "internal"
    ]
  },
  "errorCodes": [],
  "docs": "https://tabnas.dev/docs/packages",
  "repository": "https://github.com/tabnas/json",
  "versionSource": "ts/package.json",
  "translate": {
    "reads": "tree",
    "writes": "tree",
    "render": "json"
  }
}
`,
  render: Object.freeze({ entry: "json" })
})

function translate (): TranslationParts | undefined {
  return TRANSLATION
}

export {
  translate,
}

export type {
  TranslationPart,
  TranslationParts,
}
